// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxkvhqxwsughvxtbwxvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4a3ZocXh3c3VnaHZ4dGJ3eHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTQwNDgsImV4cCI6MjA2MTIzMDA0OH0.39Vqt4lfO-dbqq9LxowLnyIRWTDuVkM1Q1UykTEKSY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);